FROM python:3.11-slim

RUN pip install poetry && \
    poetry config virtualenvs.create false

WORKDIR /app

COPY pyproject.toml poetry.lock* ./

RUN poetry install --no-root --no-interaction --no-ansi

COPY scripts/ ./scripts/

CMD ["tail", "-f", "/dev/null"]