version: 2

models:
  - name: stg_transactions
    columns:
      - name: transaction_id
        tests:
          - unique
          - not_null
      - name: amount_target
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
